export const QUOTES_DB = {
  NIGHT: [
    '"La noche es la mitad de la vida, y la mejor mitad." - Johann Wolfgang von Goethe',
    '"El silencio es un amigo que jamás traiciona." - Confucio',
    '"La paciencia es amarga, pero su fruto es dulce." - Jean-Jacques Rousseau',
    '"El que no sabe guardar silencio, no sabe hablar." - Séneca',
    '"La sabiduría comienza en la maravilla." - Sócrates',
    '"Quien se conoce a sí mismo es iluminado." - Lao Tse',
    '"Lo que no me mata, me hace más fuerte." - Friedrich Nietzsche',
    '"Un viaje de mil millas comienza con un solo paso." - Lao Tse',
    '"El hombre es la medida de todas las cosas." - Protágoras',
    '"El único conocimiento verdadero es saber que no sabes nada." - Sócrates',
    '"Haz que tu mente esté libre de preocupaciones." - Proverbio Oriental',
    '"Donde hay paz, hay silencio." - Proverbio Anónimo',
    '"El descanso es el guardián de la creatividad." - Anónimo',
    '"En el centro de la quietud se halla la mayor fuerza." - Proverbio Oriental',
    '"La verdadera grandeza reside en el dominio de uno mismo." - Anónimo',
    '"Al llegar la noche, el sabio guarda sus pensamientos y el universo vela por él." - Proverbio Oriental',
    '"Lo más profundo del agua es lo más tranquilo." - Proverbio Anónimo',
    '"La oscuridad revela la luz interior." - Anónimo'
  ],
  SOCIAL: [
    '"Cuando te levantes por la mañana, piensa en el precioso privilegio de estar vivo." - Marco Aurelio',
    '"La vida es realmente simple, pero insistimos en hacerla complicada." - Confucio',
    '"Donde hay educación no hay distinción de clases." - Confucio',
    '"La felicidad depende de nosotros mismos." - Aristóteles',
    '"Las pequeñas oportunidades son a menudo el comienzo de grandes empresas." - Demóstenes',
    '"La mente no es un vaso por llenar, sino un fuego por encender." - Plutarco',
    '"Concordia, integridad y laboriosidad." - Proverbio Romano',
    '"La amistad duplica las alegrías y divide las angustias a la mitad." - Francis Bacon',
    '"No hay nada permanente excepto el cambio." - Heráclito',
    '"Saber es poder." - Francis Bacon',
    '"La bondad es el idioma que los sordos pueden oír y los ciegos pueden ver." - Mark Twain',
    '"Somos lo que hacemos día a día." - Aristóteles',
    '"El principio es la mitad de todo." - Pitágoras',
    '"Una buena charla es como el sol en el alba." - Proverbio Anónimo',
    '"Comparte tu luz, y nunca estarás en la oscuridad." - Proverbio Oriental',
    '"La comunidad es la fuerza de la humanidad." - Proverbio Anónimo',
    '"Cada día trae consigo su propio milagro." - Anónimo',
    '"Un buen comienzo hace un buen final." - Proverbio Anónimo'
  ],
  BUSINESS: [
    '"La simplicidad es la máxima sofisticación." - Leonardo da Vinci',
    '"El valor de una idea radica en el uso de la misma." - Thomas Edison',
    '"La fortuna favorece a los valientes." - Virgilio',
    '"El secreto del éxito es la constancia de propósito." - Benjamin Disraeli',
    '"No encuentres la falta, encuentra el remedio." - Proverbio Anónimo',
    '"El genio es uno por ciento de inspiración y un noventa y nueve por ciento de sudor." - Thomas Edison',
    '"La preparación es la clave del éxito." - Alexander Graham Bell',
    '"El trabajo vence todo." - Virgilio',
    '"No hay sustituto para el trabajo duro." - Thomas Edison',
    '"Si he visto más lejos, es poniéndome sobre los hombros de gigantes." - Isaac Newton',
    '"El que tiene un porqué para vivir puede soportar casi cualquier cómo." - Friedrich Nietzsche',
    '"La excelencia no es un acto, sino un hábito." - Aristóteles',
    '"Las grandes mentes discuten ideas, no eventos." - Anónimo',
    '"Aplica la estrategia y dominarás el tiempo." - Proverbio Anónimo',
    '"El agua horada la roca, no por su fuerza, sino por su constancia." - Ovidio',
    '"Haz las cosas con propósito y perfección." - Anónimo',
    '"La estrategia sin táctica es la ruta más lenta hacia la victoria." - Sun Tzu',
    '"En medio de la dificultad reside la oportunidad." - Proverbio Anónimo'
  ],
  LOUNGE: [
    '"No es que tengamos poco tiempo, sino que perdemos mucho." - Séneca',
    '"La vida no se mide por las veces que respiras, sino por los momentos que te dejan sin aliento." - Anónimo',
    '"La belleza de las cosas existe en el espíritu de quien las contempla." - David Hume',
    '"Elige un trabajo que te guste, y no tendrás que trabajar ni un día de tu vida." - Confucio',
    '"La música es la aritmética de los sonidos, como la óptica es la geometría de la luz." - Claude Debussy',
    '"La paz viene de adentro. No la busques afuera." - Buda',
    '"En el arte como en el amor, el instinto es suficiente." - Anatole France',
    '"Nada es permanente a excepción del cambio." - Heráclito',
    '"El arte es el reflejo de lo divino en la tierra." - Anónimo',
    '"La naturaleza no hace nada en vano." - Aristóteles',
    '"Lo bello es un gozo eterno." - John Keats',
    '"Es tiempo de saborear la tranquilidad y el instante." - Proverbio Anónimo',
    '"Un atardecer es un buen momento para reflexionar." - Anónimo',
    '"La pausa es tan importante como la acción." - Proverbio Anónimo',
    '"El reposo del sol invita a la serenidad de la mente." - Anónimo',
    '"Fluye como el agua, y encontrarás tu camino." - Lao Tse',
    '"En cada final hay un nuevo comienzo oculto." - Proverbio Anónimo',
    '"Disfruta la transición, pues en ella habita el equilibrio." - Anónimo'
  ],
  PREMIUM: [
    '"Estamos hechos de la misma materia que los sueños." - William Shakespeare',
    '"Lo que es hermoso es bueno, y el que es bueno pronto será hermoso." - Safo de Lesbos',
    '"Los clásicos son inmortales en el alma humana." - Anónimo',
    '"El verdadero viaje de descubrimiento consiste en tener nuevos ojos." - Marcel Proust',
    '"Saber envejecer es la obra maestra de la sabiduría." - Henri-Frédéric Amiel',
    '"El estilo es el vestido del pensamiento." - Séneca',
    '"La verdadera elegancia es la simplicidad perfeccionada." - Anónimo',
    '"La paz se encuentra al abrazar la vida por completo." - Proverbio Anónimo',
    '"La imaginación es el principio de la creación." - Proverbio Anónimo',
    '"Reconocer la propia ignorancia es el primer paso hacia la sabiduría." - Sócrates',
    '"La excelencia es un arte ganado mediante el entrenamiento." - Aristóteles',
    '"Un ojo hermoso hace a los demás hermosos." - Ralph Waldo Emerson',
    '"La calidad no es un acto, es un hábito." - Aristóteles',
    '"Aquello que se cultiva con esmero florece con grandeza." - Proverbio Anónimo',
    '"El detalle es lo que distingue al artesano del artista." - Anónimo',
    '"El refinamiento del espíritu se refleja en el aura." - Proverbio Oriental',
    '"Quien busca la excelencia encuentra la atemporalidad." - Anónimo',
    '"El arte de vivir es el arte de saber dar valor a las cosas invisibles." - Anónimo'
  ]
};
